steps:
  # Build container
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/$_PROJECT_ID/${_AR_REPO}/${_IMAGE}",
        ".",
      ]
    # Push container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "${_LOCATION}-docker.pkg.dev/$_PROJECT_ID/${_AR_REPO}/${_IMAGE}"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deploy.yaml
      - --location=us-central1
      - --cluster=cluster-test-public-regional
timeout: 660s
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: projects/georgef-sandbox/locations/us-central1/workerPools/private-pool
# kubectl run -it --rm nginx --image=nginx -- sh
