apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-host-details-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: show-host-details-deployment
  template:
    metadata:
      labels:
        app: show-host-details-deployment
    spec:
      containers:
        - name: show-host-details-container
          image: us-central1-docker.pkg.dev/georgef-sandbox/show-host-details/show-host-details
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: show-host-details-service
spec:
  type: ClusterIP
  selector:
    app: show-host-details-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
