apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ssl
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "hello-app-static-ip"
    # kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - secretName: hello-app-secret
  defaultBackend:
    service:
      name: hello-app-svc-1
      port:
        number: 8080
  rules:
    - http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: hello-app-svc-1
                port:
                  number: 8080
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: hello-app-svc-2
                port:
                  number: 8080
